name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install DuckDB
      run: |
        wget https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip
        unzip duckdb_cli-linux-amd64.zip
        sudo mv duckdb /usr/local/bin/duckdb
        sudo chmod +x /usr/local/bin/duckdb

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
